config/routes.rb
Rails.application.routes.draw do

  resources :attendances, only: [] do
    member do
      patch :update_attendance_request
    end
  end

  resources :users do  # CSV出力用のルートを追加
    member do
      get :export_csv # CSV出力用のアクション名を選択
    end
  end

  get 'bases/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'working_employees', to: 'users#working_employees', as: 'working_employees'

  resources :users do
    collection { post :import} #CSVファイルインポート
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendance_review'
    end
    
    resources :attendances, only: :update do
      member do
        patch :update_attendance_request
        get :approved_logs
        delete :reset_approved_logs
      end
    end
  end

  resources :bases

  resources :overtime_requests, only: [:new, :create] do
    member do
      patch :update
      patch :approve_overtime
    end
  end

  resources :monthly_approvals, only: [:create, :update]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  validates :employee_number, presence: true, uniqueness: true, format: { with: /\A\d+\z/, message: "は数字のみ使用できます" }, length: { maximum: 6 }
  validates :uid, presence: true, uniqueness: true
  validates :basic_work_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

   # 上長を取得するスコープ
   scope :superiors, -> { where(superior: true) }

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
    if ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

  # CSVインポート
  def self.import(file)
    if file.present? && file.respond_to?(:path)
      CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
        existing_user = User.find_by(email: row["email"]) # メールアドレスをキーにして既存のユーザーを探す
        unless existing_user
        user = User.new
        user.attributes = row.to_hash.slice(*updatable_attributes)
        user.save!
        end
      end
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end

end

app/controllers/users_controller.rb
require 'csv'

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :working_employees]
  before_action :correct_user, only: [:show, :edit]
  before_action :correct_user_or_admin, only: [:update]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info, :working_employees]
  before_action :set_one_month, only: :show
  before_action :set_superiors, only: [:show]

  def index
    @users = User.where(admin: false).paginate(page: params[:page])
  end

  def show
    if params[:date]
      @first_day = Date.parse(params[:date]).beginning_of_month
    else
      @first_day = Date.current.beginning_of_month
    end
    
    @attendances = @user.attendances.where(worked_on: @first_day..@first_day.end_of_month).order(:worked_on)
    @worked_sum = @attendances.where.not(started_at: nil).count

    @monthly_approval_requests = Attendance.where(monthly_approval_approver_id: current_user.id, 
                                                  monthly_approval_status: "monthly_approval_pending")
                                              .group_by { |m| [m.user_id, m.worked_on.beginning_of_month] }
                                              .map { |key, values| values.find { |v| v.worked_on == key[1] } }
    @monthly_approval_requests.compact!  # nil の要素を取り除く
    
    @monthly_request_counts = @monthly_approval_requests.group_by { |request| request.user }.transform_values do |requests|
      requests.count
    end

    @attendance_requests = Attendance.where(attendance_approver_id: current_user.id, attendance_status: "attendance_pending")
    @attendance_requests_counts = @attendance_requests.count

    @overtime_requests = Attendance.where(overtime_approver_id: current_user.id, overtime_status: "overtime_pending")
    @unapproved_overtime_requests = Attendance.where(overtime_approver_id: @user.id, overtime_status: Attendance.overtime_statuses[:overtime_pending]).count || 0

    @superiors = User.where(superior: true).where.not(id: current_user.id)

    @monthly_approval_status = if @user
      monthly_approval = @user.attendances.find_by(worked_on: @first_day.beginning_of_month)
      if monthly_approval
        case monthly_approval.monthly_approval_status
        when "monthly_approval_pending"
          "申請中"
        when "monthly_approval_no_request"
          "未"
        when "monthly_approval_approved"
          "承認済み"
        when "monthly_approval_declined"
          "否認"
        else
          "その他のステータス"
        end
      else
        "データなし"  # 初日の月次承認データが存在しない場合のデフォルト値
      end
    else
      "ユーザーが存在しません"  # ユーザーが存在しない場合のデフォルト値
    end
                          
    approver_ids = @attendances.map(&:monthly_approval_approver_id).compact.uniq
    @monthly_approval_approvers = User.where(id: approver_ids)

    @grouped_monthly_approval_requests = @monthly_approval_requests.group_by(&:user)
  end

  def new
    @user = User.new(user_params)
  end

  def create
    @user = User.new(user_params)
    set_designated_times_for_user(@user) if @user.designated_work_start_time.nil? && @user.designated_work_end_time.nil?
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      if params[:from] == 'user_list'
        redirect_to users_path
      else
      redirect_to @user
      end
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報は更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end

  def working_employees
    @working_employees = User.joins(:attendances).where(attendances: { worked_on: Date.current }).where.not(attendances: { started_at: nil }).where(attendances: { finished_at: nil })
  end

  def import
    if params[:file].present?
      User.import(params[:file])
      flash[:success] = "ユーザーを追加しました。"
    else
      flash[:danger] = "ファイルを選択してください"
    end
      redirect_to users_path
  end

  def export_csv
    @user = User.find(params[:id])
    year = params[:year].to_i
    month = params[:month].to_i
    start_date = Date.new(year, month, 1)
    end_date = start_date.end_of_month
    @attendances = @user.attendances.where(worked_on: start_date..end_date)

    respond_to do |format|
      format.csv do
        # CSV出力の処理を記述
        csv_data = CSV.generate(headers: true) do |csv|
          # ユーザーの勤怠情報をCSVに出力する例：
          csv << ["日付", "出社時間", "退社時間"]

          @attendances.each do |attendance|
            if attendance.attendance_status == "attendance_approved"
              csv << [
                attendance.worked_on,
                attendance.started_at,
                attendance.finished_at
              ]
            else
              csv << [attendance.worked_on, nil, nil]
            end
          end
        end

        filename = "#{@user.name}の#{I18n.l(start_date, format: :middle)}分勤怠情報.csv" # ファイル名を動的に生成
        send_data csv_data, filename: filename, type: "text/csv"
      end
    end
  end

  def attendance_review
    # ここで該当ユーザーの勤怠データを取得します。
    @user = User.find(params[:id])
    
    # 勤怠データの取得や処理のロジックを記述します。
    # 例: 1か月分の勤怠データの取得
    if params[:date]
      @first_day = Date.parse(params[:date]).beginning_of_month
    else
      @first_day = Date.current.beginning_of_month
    end
    
    @last_day = @first_day.end_of_month
    @attendances = @user.attendances.where(worked_on: @first_day..@first_day.end_of_month).order(:worked_on)

    approver_ids = @attendances.map(&:monthly_approval_approver_id).compact.uniq
    @monthly_approval_approvers = User.where(id: approver_ids)

    @monthly_approval_status = if @user
      monthly_approval = @user.attendances.find_by(worked_on: @first_day.beginning_of_month)
      if monthly_approval
        case monthly_approval.monthly_approval_status
        when "monthly_approval_pending"
          "申請中"
        when "monthly_approval_no_request"
          "未"
        when "monthly_approval_approved"
          "承認済み"
        when "monthly_approval_declined"
          "否認"
        else
          "その他のステータス"
        end
      else
        "データなし"  # 初日の月次承認データが存在しない場合のデフォルト値
      end
    else
      "ユーザーが存在しません"  # ユーザーが存在しない場合のデフォルト値
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :password, :password_confirmation, :employee_number, :uid, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end

    def basic_info_params
      params.require(:user).permit(:affiliation, :basic_work_time, :work_time)
    end

    def set_superiors
      @superiors = User.where(superior: true).where.not(id: current_user.id)
    end

    def set_designated_times_for_user(user)
      user.designated_work_start_time = Time.current.change(hour: 9, min: 0, sec: 0)
      user.designated_work_end_time = Time.current.change(hour: 18, min: 0, sec: 0)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :affiliation, class: "form-control" %>

            <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_work_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', user: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報編集") %>
<% provide(:button_text, '更新') %>

<div class="container">
  <h1>基本情報編集</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
        <%= render 'shared/error_messages', user: @user %>

        <%= f.label :name, class: "label-#{yield(:class_text)}" %>
        <p><%= @user.name %></p>

        <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
        <%= f.text_field :affiliation, class: "form-control" %>

        <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
        <%= f.time_field :basic_work_time, class: "form-control" %>

        <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
        <%= f.time_field :work_time, class: "form-control form-spacing" %>

        <div class="center">
          <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
          <%= link_to 'キャンセル', users_url, class: "btn btn-default btn-#{yield(:class_text)}" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td colspan="2">
      <%= link_to "◀", user_path(date: @first_day.prev_month), class: " btn btn-info" %>
      <%= l(@first_day, format: :middle) %> 時間管理表
      <%= link_to "▶", user_path(date: @first_day.next_month), class: " btn btn-info" %>
    </td>
    <td>指定勤務開始時間<%= @user.designated_work_start_time.strftime("%H:%M") %><br>指定勤務終了時間 <%= @user.designated_work_end_time.strftime("%H:%M") %></td>
      <td colspan="2">基本時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td>初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td colspan="2">所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード：<%= @user.employee_number %></td>
      <td>出勤日数： <%= @worked_sum %>日</td>
      <td>締め：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>
<div class="btn-users-show">
  <% if current_user.superior? %>
    <div>
      <% if @monthly_approval_requests.present? %>
        <%= link_to "【所属長承認申請のおしらせ】", "#monthlyApprovalCheckModal", class: "btn #{'notification-link' if @monthly_request_counts.values.sum > 0}", data: { toggle: 'modal' } %>
        <% if @monthly_request_counts.values.sum > 0 %>
          <span class="notification-count"><%= @monthly_request_counts.values.sum %>件の通知があります</span>
        <% end %>
      <% else %>
        <%= link_to "【所属長承認申請のおしらせ】", "#", class: "btn" %>
      <% end %>
    </div>
    <div>
      <% if @attendance_requests.present? %>
        <%= link_to "【勤怠変更のお知らせ】", "#attendanceCheckModal", class: "btn #{'notification-link' if @attendance_requests_counts > 0}", data: { toggle: 'modal' } %>
        <% if @attendance_requests_counts > 0 %>
          <span class="notification-count"><%= @attendance_requests_counts %>件の通知があります</span>
        <% end %>
      <% else %>
        <%= link_to "【勤怠変更のお知らせ】", "#", class: "btn" %>
      <% end %>
    </div>
    <div>
      <% if @overtime_requests.present? %>
        <%= link_to "【残業申請のお知らせ】", "#overtimeCheckModal", class: "btn #{'notification-link' if @unapproved_overtime_requests > 0}", data: { toggle: 'modal' } %>
        <% if @unapproved_overtime_requests > 0 %>
          <span class="notification-count"><%= @unapproved_overtime_requests %>件の通知があります</span>
        <% end %>
      <% else %>
      <%= link_to "【残業申請のお知らせ】", "#", class: "btn" %>
      <% end %>
    </div>    
  <% end %>

  <div class="d-flex justify-content-start mb-2">
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
    <%= link_to "CSV出力", export_csv_user_path(@user, year: @first_day.year, month: @first_day.month, format: :csv), class: "btn btn-primary me-2" %>
  </div>
  <div>
    <%= link_to "勤怠修正ログ(承認済み)", approved_logs_user_attendance_path(current_user), class: "btn btn-primary" %>
  </div>
</div>

<div>
  <% total_working_hours = 0.0 %>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="7">【実績】</th>
        <th colspan="6">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="2">出社</th>
        <th></th>
        <th colspan="2">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2", colspan="2">指示書確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td>
            <%= link_to "残業申請", "#overtimeModal-#{day.worked_on}", class: "btn btn-primary overtime-request-btn", "data-toggle" => "modal", data: { date: day.worked_on } %>
          </td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= day_color_class(day.worked_on.wday) %>">
            <%= $days_of_the_week[day.worked_on.wday] %>
          </td>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= l(day.started_at, format: :minute) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td>
            <%= format_time_hours(day.finished_at, day.next_day) %>
          </td>
          <td><%= l(day.finished_at, format: :minute) if day.finished_at.present? %></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <% working_hours = ((day.finished_at - day.started_at) / 3600).to_i %>
              <% working_minutes = ((day.finished_at - day.started_at) / 60).to_i % 60 %>
              <% total_working_hours += working_hours + working_minutes / 60.0 %>
              <%= format("%d:%02d", working_hours, working_minutes) %> <!-- 時:分 の形式で出力 -->
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td>
            <%= format_time_hours(day.overtime_end_at, day.next_day) %>
          </td>
          <td><%= day.overtime_end_at ? day.overtime_end_at.strftime('%M') : '' %></td>
          <td>
          <% if day.overtime_end_at.present? %>
            <% designated_end_time_corrected_date = @user.designated_work_end_time.change(year: day.worked_on.year, month: day.worked_on.month, day: day.worked_on.day) %>
            <% overtime_duration = day.overtime_end_at - designated_end_time_corrected_date %>
            <% overtime_hours = (overtime_duration / 3600).to_i %>
            <% overtime_minutes = ((overtime_duration % 3600) / 60).to_i %>
            
            <% if overtime_duration < 0 %>
                -<%= '%.2f' % (overtime_hours.abs + overtime_minutes.abs / 60.0) %>
            <% else %>
                <%= '%.2f' % (overtime_hours + overtime_minutes / 60.0) %>
            <% end %>
          <% end %>
          </td>
          <td><%= day.overtime_task ? day.overtime_task : '' %></td>
          <td colspan="2">
            <% overtime_status_text = case day.overtime_status
              when "overtime_pending" then "残業申請中"
              when "overtime_approved" then "残業申請承認済"
              when "overtime_declined" then "残業申請否認"
              else ""
              end %>
              
            <% attendance_status_text = case day.attendance_status
              when "attendance_pending" then "勤怠編集申請中"
              when "attendance_approved" then "勤怠編集承認済"
              when "attendance_declined" then "勤怠編集否認"
              else ""
              end %>

            <% if day.overtime_status == "overtime_no_request" %>
              <%= "" %>
            <% elsif day.overtime_status.present? %>
              <%= "【#{day.overtime_approver.name if day.overtime_approver.present?}】#{overtime_status_text}" %>             
            <% end %>
            <br>
            <% if day.attendance_status == "attendance_no_request" %>
              <% "" %>
            <% elsif day.attendance_status.present? %>
              <%= "【#{day.attendance_approver.name if day.attendance_approver.present?}】#{attendance_status_text}" %>
            <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <td>総合勤務時間</td>
        <td colspan="8"></td>
        <td>合計在社時間</td>
        <td colspan="5"></td>
        <td rowspan="2">
          <div class="mb-2">
            所属長承認：
            <% if @monthly_approval_status == "未" %>
              <span>未</span>
            <% elsif @monthly_approval_status == "申請中" %>
              <span><%= @monthly_approval_approvers.map(&:name).join(", ") %>へ 申請中</span>
            <% elsif @monthly_approval_status == "承認済み" %>
              <span><%= @monthly_approval_approvers.map(&:name).join(", ") %>から 承認済み</span>
            <% elsif @monthly_approval_status == "否認" %>
              <span><%= @monthly_approval_approvers.map(&:name).join(", ") %>から 否認</span>
            <% else %>
              <span class="badge badge-secondary"><%= @monthly_approval_status %></span>
            <% end %>
          </div>
            <%= form_with(url: monthly_approvals_path, method: :post, local: true) do %>
              <%= hidden_field_tag :first_day, @first_day %>
              <div class="mb-2">
                <select class="form-control" name="superior_user_id">
                  <option value=""></option>
                  <% @superiors.each do |superior| %>
                    <option value="<%= superior.id %>"><%= superior.name %></option>
                  <% end %>
                </select>
              </div>
              <div>
                <%= submit_tag "申請", class: "btn btn-primary full-size-btn" %>
              </div>
            <% end %>        
        </td>
      </tr>
      <tr>
        <td><%= format_basic_info(@user.basic_work_time).to_f * @worked_sum %></td>
        <td colspan="8"></td>
        <td><%= format("%.2f", total_working_hours) %></td>
        <td colspan="5"></td>
      </tr>
    </tfoot>
  </table>

  <% @attendances.each do |day| %>
    <%= render partial: "overtime_requests/new_overtime_requests", locals: { day: day } %>
  <% end %>    

  <%= render partial: "monthly_approvals/monthly_application" %>
  <%= render partial: "attendances/attendance_requests_application" %>
  <%= render partial: "overtime_requests/overtime_application" %>

</div>

app/views/users/working_employees.html.erb
<% provide(:title, 'Working Employees') %>
<h1>出勤中社員一覧</h1>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>社員番号</th>
            <th>名前</th>
          </tr>
        </thead>
        <tbody>
          <% @working_employees.each do |employee| %>
            <tr>
              <td><%= employee.employee_number %></td>
              <td><%= employee.name %></td>
            </tr>    
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>