config/routes.rb
Rails.application.routes.draw do

  resources :attendances, only: [] do
    member do
      patch :update_attendance_request
    end
  end

  resources :users do  # CSV出力用のルートを追加
    member do
      get :export_csv # CSV出力用のアクション名を選択
    end
  end

  get 'bases/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'working_employees', to: 'users#working_employees', as: 'working_employees'

  resources :users do
    collection { post :import} #CSVファイルインポート
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendance_review'
    end
    
    resources :attendances, only: :update do
      member do
        patch :update_attendance_request
        get :approved_logs
        delete :reset_approved_logs
      end
    end
  end

  resources :bases

  resources :overtime_requests, only: [:new, :create] do
    member do
      patch :update
      patch :approve_overtime
    end
  end

  resources :monthly_approvals, only: [:create, :update]
end

app/controllers/overtime_requests_controller.rb
class OvertimeRequestsController < ApplicationController
  before_action :set_superiors, only: [:new, :update]

  def new
    @attendance = Attendance.new
  end

  def update
    @attendance = Attendance.find(params[:id]) 

    worked_on_datetime = @attendance.worked_on.in_time_zone('Asia/Tokyo').to_datetime
    year = worked_on_datetime.year
    month = worked_on_datetime.month
    day = worked_on_datetime.day
    @attendance.assign_attributes(attendance_params)
    
    if params[:attendance][:next_day].to_i == 1
      @attendance.next_day = true
      worked_on_datetime = worked_on_datetime.advance(days: 1)
    else
      @attendance.next_day = false
    end

    hour = params[:attendance]["overtime_end_at(4i)"].to_i
    minute = params[:attendance]["overtime_end_at(5i)"].to_i

    overtime_end_at = worked_on_datetime.change(hour: hour, min: minute)

    @attendance.overtime_end_at = overtime_end_at
    @attendance.overtime_pending!
  
    if @attendance.save
      # 成功時の処理
      flash[:success] =  "残業申請が成功しました。"
      redirect_to user_path(current_user)
    else
      # エラー時の処理
      flash[:danger] =  "残業申請に失敗しました。"
      render :edit
    end
  end

  def approve_overtime
    approved = false  # フラグを使用してアプローブが行われたかを確認します

    params[:overtime_requests].each do |id, overtime_request_params|
      attendance = Attendance.find(id)

      if overtime_request_params["approval_status"] == "1"
        attendance.update(overtime_status: overtime_request_params["overtime_status"])
        approved = true  # アプローブがあればフラグをtrueに設定します
      end
    end

    if approved
      flash[:success] = "残業申請の変更を行いました。"
    end

      redirect_to user_path(current_user)
      
  end

  private

  def attendance_params
    params.require(:attendance).permit(:worked_on, :overtime_task, :overtime_approver_id, :overtime_end_at, :next_day)
  end

  def approve_overtime_params
    params.require(:attendance).permit(:overtime_status, :approval_status)
  end

  def set_superiors
    @superiors = User.where(superior: true).where.not(id: current_user.id)
  end
end

app/helpers/overtime_requests_helper.rb
module OvertimeRequestsHelper
end

app/views/overtime_requests/_new_overtime_requests.html.erb
<%= form_with(model: day, local: true, url: overtime_request_path(day), method: :patch) do |f| %>
  <div class="modal fade custom-modal" id="overtimeModal-<%= day.worked_on %>" tabindex="-1" role="dialog" aria-labelledby="overtimeModalLabel-<%= day.worked_on %>" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <h4 class="text-center">【残業申請】</h4>
        <div class="table-responsive">
          <table class="table table-condensed table-hover">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th colspan="2">終了予定時間</th>
                <th>翌日</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= l(day.worked_on, format: :short) %></td>
                <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                <td colspan="2">
                  <div class="time-input-container">
                    <%= f.time_select :overtime_end_at, {}, { class: 'time-input' } %>
                  </div>
                </td>
                <td><%= f.check_box :next_day %></td>
                <td><%= f.text_area :overtime_task, placeholder: '業務処理内容を入力' %></td>
                <td><%= f.select :overtime_approver_id, @superiors.map { |u| [u.name, u.id] }, { prompt: "上長を選択" } %></td>                
              </tr>
            </tbody>
          </table>
          <%= f.submit '変更を送信する', class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/overtime_requests/_overtime_application.html.erb
<div class="modal fade" id="overtimeCheckModal" tabindex="-1" role="dialog" aria-labelledby="overtimeCheckModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content"> 
    <%= form_for :overtime_request, url: approve_overtime_overtime_request_path, method: :patch do |f| %>
      <% @overtime_requests.group_by(&:user).each do |user, requests| %>
          <h4 class="text-center">【<%= user.name %>からの申請】</h4>
        <div class="table-responsive">            
            <table class="table table-condensed table-hover">  
              <thead>  
                <tr>
                  <td>日付</td>
                  <td>曜日</td>
                  <td>終了予定時間</td>
                  <td>指定勤務終了時間</td>
                  <td>時間外時間</td>
                  <td>業務処理内容</td>
                  <td>指示者確認㊞</td>
                  <td>変更</td>
                  <td>勤怠を確認する</td>
                </tr>
              </thead>
              <tbody> 
              <% requests.each do |overtime_request| %>
                <%= fields_for "overtime_requests[#{overtime_request.id}]", overtime_request do |or_fields| %>
                  <tr>
                    <td><%= overtime_request.worked_on.strftime("%-m/%-d") %></td>  
                    <td><%= $days_of_the_week[overtime_request.worked_on.wday] %></td>
                    <td>
                      <%= format_time(overtime_request.overtime_end_at, overtime_request.next_day?) %>
                    </td>
                    <td><%= overtime_request.user.designated_work_end_time.strftime("%H:%M") if overtime_request.user.designated_work_end_time.present? %></td>
                    <%
                    designated_end_time_corrected_date = overtime_request.user.designated_work_end_time.change(year: overtime_request.worked_on.year, month: overtime_request.worked_on.month, day: overtime_request.worked_on.day)
                    
                    overtime_duration = overtime_request.overtime_end_at - designated_end_time_corrected_date
                    overtime_hours = (overtime_duration / 3600).to_i
                    overtime_minutes = ((overtime_duration % 3600) / 60).to_i
                    %>
                    <td>
                      <% if overtime_duration < 0 %>
                        -<%= '%.2f' % (overtime_hours.abs + overtime_minutes.abs / 60.0) %>
                      <% else %>
                        <%= '%.2f' % (overtime_hours + overtime_minutes / 60.0) %>
                      <% end %>
                    </td>
                    <td><%= overtime_request.overtime_task %></td>
                      <td>
                        <%= or_fields.select :overtime_status, {'なし' => 'overtime_no_request',
                                                                '申請中' => 'overtime_pending',
                                                                '承認' => 'overtime_approved',
                                                                '否認' => 'overtime_declined'
                                                                }, {}, { class: 'form-control' } %>
                      </td>
                      <td><%= or_fields.check_box :approval_status %></td>
                      <td><%= link_to '確認', attendance_review_user_path(overtime_request.user, date: overtime_request.worked_on), class: 'btn btn-primary' %>
                  </tr> 
                <% end %>   
              <% end %>
              </tbody>      
            </table>
        </div>
      <% end %> 
      <div class="text-center">      
        <%= f.submit '変更を送信する', class: 'btn btn-primary btn-lg' %>     
      </div>
    <% end %>          
    </div>
  </div>
</div>