config/routes.rb
Rails.application.routes.draw do

  resources :attendances, only: [] do
    member do
      patch :update_attendance_request
    end
  end

  resources :users do  # CSV出力用のルートを追加
    member do
      get :export_csv # CSV出力用のアクション名を選択
    end
  end

  get 'bases/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'working_employees', to: 'users#working_employees', as: 'working_employees'

  resources :users do
    collection { post :import} #CSVファイルインポート
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendance_review'
    end
    
    resources :attendances, only: :update do
      member do
        patch :update_attendance_request
        get :approved_logs
        delete :reset_approved_logs
      end
    end
  end

  resources :bases

  resources :overtime_requests, only: [:new, :create] do
    member do
      patch :update
      patch :approve_overtime
    end
  end

  resources :monthly_approvals, only: [:create, :update]
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  before_update :store_before_change_time

  # approverに関するアソシエーション
  belongs_to :overtime_approver, class_name: "User", optional: true, foreign_key: "overtime_approver_id"
  belongs_to :monthly_approval_approver, class_name: "User", optional: true, foreign_key: "monthly_approval_approver_id"
  belongs_to :attendance_approver, class_name: "User", optional: true, foreign_key: "attendance_approver_id"

  validates :worked_on, presence: true

  validates :note, length: { maximum: 50 }

  validates :overtime_task, length: { maximum: 100 }

  enum attendance_status: {
    attendance_no_request: 0, 
    attendance_pending: 1, 
    attendance_approved: 2, 
    attendance_declined: 3 
  }

enum overtime_status: {
  overtime_no_request: 0, 
  overtime_pending: 1, 
  overtime_approved: 2, 
  overtime_declined: 3 
}

enum monthly_approval_status: {
  monthly_approval_no_request: 0, 
  monthly_approval_pending: 1, 
  monthly_approval_approved: 2, 
  monthly_approval_declined: 3 
}

scope :monthly_approval_pending, -> { where(monthly_approval_status: "monthly_approval_pending") }
scope :first_day_of_month, -> { where("strftime('%d', worked_on) = '01'") }
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  validate :overtime_end_at_validity

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end

  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end

  def overtime_end_at_validity
    # 例: 出勤時間よりも前の残業終了時間は無効
    if started_at.present? && overtime_end_at.present? && started_at > overtime_end_at
      errors.add(:overtime_end_at, "は出勤時間よりも後である必要があります")
    end
  end

  private

  def store_before_change_time
    if started_at_changed?
      self.started_at_before_change = started_at_was
      self.first_started_at_before_change ||= started_at_was
    end

    if finished_at_changed?
      self.finished_at_before_change = finished_at_was
      self.first_finished_at_before_change ||= finished_at_was
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :approved_logs]
  before_action :logged_in_user, only: [:update, :edit_one_month, :approved_logs]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: :edit_one_month
  before_action :set_superiors, only: [:edit_one_month, :update_one_month]

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end

  def edit_one_month
  end

  def update_one_month
    errors = []
    
    begin
      ActiveRecord::Base.transaction do
        attendances_params.each do |id, item|
          @attendance = Attendance.find(id)
          @attendance.attendance_approver_id = item[:attendance_approver_id]
        
          if @attendance.attendance_approver_id.present?  # 指示確認者が指定されている場合のみエラーチェックを行う
  
            worked_on_datetime = @attendance.worked_on.in_time_zone('Asia/Tokyo').to_datetime
      
            started_hour, started_min = extract_time_from(item[:started_at])
            finished_hour, finished_min = extract_time_from(item[:finished_at])

            if started_hour.nil?
              item[:started_at] = nil
            else
              item[:started_at] = worked_on_datetime.change(hour: started_hour, min: started_min)
            end

            if finished_hour.nil?
              item[:finished_at] = nil
            else
              item[:finished_at] = worked_on_datetime.change(hour: finished_hour, min: finished_min)
            end

            if item[:next_day].to_i == 1
              @attendance.next_day = true
              worked_on_datetime = worked_on_datetime.advance(days: 1)

              if item[:finished_at].present?
                item[:finished_at] = worked_on_datetime.change(hour: finished_hour, min: finished_min)
              end
            else
              @attendance.next_day = false
            end

            if item[:started_at].present? && item[:finished_at].blank?
              errors << "#{@attendance.worked_on}の退社時間が未入力です。"
            elsif item[:started_at].blank? && item[:finished_at].present?
              errors << "#{@attendance.worked_on}の出社時間が未入力です。"
            else
                     
              # 送信された値（これはフォームから送信されたパラメータを取得）
              new_started_at = item[:started_at]
              new_finished_at = item[:finished_at]
              # 編集前の時間と送信された時間が同じであるかどうかをチェック
              if @attendance.started_at == new_started_at && @attendance.finished_at == new_finished_at
               
              else
                @attendance.started_at = item[:started_at]
                @attendance.finished_at = item[:finished_at]
                @attendance.note = item[:note]
                @attendance.attendance_approver_id = item[:attendance_approver_id]

                @attendance.attendance_pending!
                @attendance.save!           
              end      
            end
          end
        end
      end

    rescue => e
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      flash[:danger] << "エラー: #{e.message}"
    end
  
    if errors.empty?
      flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
      redirect_to user_url(date: params[:date])
    else
      flash[:danger] = errors.join("<br>").html_safe
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
    end
  end

  def update_attendance_request
    success = false # フラグを用意して、更新が成功したかどうかを追跡

    params[:attendance_requests].each do |id, attendance_params|
      attendance = Attendance.find(id)

      if attendance_params["approval_status"] == "1" && attendance_params["attendance_status"] == "attendance_approved"
        success = attendance.update(attendance_status: attendance_params["attendance_status"],
                                    display_in_logs: true)
      elsif attendance_params["approval_status"] == "1"
        success = attendance.update(attendance_status: attendance_params["attendance_status"])
      end
    end

    if success
      flash[:success] = '勤怠変更申請を更新しました。'
    else
      flash[:warning] = '勤怠変更申請の更新に問題がありました。'
    end

    redirect_to user_path(current_user)
  end

  def approved_logs
    base_query = Attendance.attendance_approved.where(user_id: params[:user_id], display_in_logs: true)

    if params[:search].present? && params[:search][:year].present? && params[:search][:month].present? && valid_year_month?(params[:search][:year], params[:search][:month])
      start_date = Date.new(params[:search][:year].to_i, params[:search][:month].to_i, 1)
      end_date = start_date.end_of_month
       
      @approved_attendances = base_query.where(worked_on: start_date..end_date)
    else
      @approved_attendances = base_query
    end
  end

  def reset_approved_logs
    @user = User.find(params[:user_id]) # 対象のユーザーを見つける
    @user.attendances.where(display_in_logs: true).update_all(display_in_logs: false)  # そのユーザーの、表示すべき履歴ログを非表示にする
    flash[:success] = "履歴ログをリセットしました。"
    redirect_to approved_logs_user_attendance_path(@user)
  end

  def approve_attendance
    update(attendance_status: :attendance_approved)
  end
  
  private
    # 1ヶ月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note, :next_day, :attendance_approver_id, :attendance_status, :approval_status])[:attendances]
    end

    # beforeフィルター

    # 管理権限者、または現在ログインしているユーザーを許可します。
    def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end
    end

    def extract_time_from(time_string)
      hour, minute = time_string.split(":").map(&:to_i)
      return hour, minute
    end

    def set_superiors
      @superiors = User.where(superior: true).where.not(id: current_user.id)
    end

    def valid_year_month?(year, month)
      (year.to_i.to_s == year) && (month.to_i.to_s == month) && (1..12).include?(month.to_i)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end

end

app/views/attendances/_attendance_requests_application.html.erb
<div class="modal fade" id="attendanceCheckModal" tabindex="-1" role="dialog" aria-labelledby="attendanceCheckModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <%= form_for :attendance_request, url: update_attendance_request_attendance_path, method: :patch do |f| %>
        <% @attendance_requests.group_by(&:user).each do |user, requests| %>
            <h4 class="text-center">【<%= user.name %>からの勤怠変更申請】</h4>
            <div class="table-responsive">
              <table class="table table-condensed table-hover">
                <thead>
                  <tr>
                    <th rowspan="3">日付</th>
                    <th rowspan="3">曜日</th>
                    <th colspan="4">変更前</th>
                    <th colspan="4">変更後</th>
                    <th rowspan="3">備考</th>
                    <th rowspan="3">指示者確認㊞</th>
                    <th rowspan="3">変更</th>
                    <th rowspan="3">勤怠を確認する</th>
                  </tr>
                  <tr>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                  </tr>
                  <tr>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                  </tr>
                </thead>
                <tbody>
                    <% requests.each do |attendance_request| %>
                      <%= fields_for "attendance_requests[#{attendance_request.id}]", attendance_request do |ar_fields| %>
                      <tr>
                        <td><%= l(attendance_request.worked_on, format: :short) %></td>
                        <td><%= $days_of_the_week[attendance_request.worked_on.wday] %></td>
                        <td>
                          <% if same_day?(attendance_request.started_at_before_change, attendance_request.worked_on) %>
                            <%= format_time_hours(attendance_request.started_at_before_change) %>
                          <% else %>
                            <%= format_time_hours(attendance_request.started_at_before_change, true) %>
                          <% end %>
                        </td>
                        <td><%= attendance_request.started_at_before_change&.strftime('%M') %></td>
                        <td>
                          <% if same_day?(attendance_request.finished_at_before_change, attendance_request.worked_on) %>
                            <%= format_time_hours(attendance_request.finished_at_before_change) %>
                          <% else %>
                            <%= format_time_hours(attendance_request.finished_at_before_change, true) %>
                          <% end %>
                        </td>
                        <td><%= attendance_request.finished_at_before_change&.strftime('%M') %></td>
                        <td>
                          <% if same_day?(attendance_request.started_at, attendance_request.worked_on) %>
                            <%= format_time_hours(attendance_request.started_at) %>
                          <% else %>
                            <%= format_time_hours(attendance_request.started_at, true) %>
                          <% end %>
                        </td>
                        <td><%= attendance_request.started_at.strftime('%M') %></td>
                        <td>
                          <% if same_day?(attendance_request.finished_at, attendance_request.worked_on) %>
                            <%= format_time_hours(attendance_request.finished_at) %>
                          <% else %>
                            <%= format_time_hours(attendance_request.finished_at, true) %>
                          <% end %>
                        </td>
                        <td><%= attendance_request.finished_at.strftime('%M') %></td>
                        <td><%= attendance_request.note %></td>
                        <td>
                          <%= ar_fields.select :attendance_status, {'なし' => 'attendance_no_request',
                                                                    '申請中' => 'attendance_pending',
                                                                    '承認' => 'attendance_approved',
                                                                    '否認' => 'attendance_declined'
                                                                  }, {}, { class: 'form-control' } %>
                        </td>
                        <td><%= ar_fields.check_box :approval_status %></td>
                        <td><%= link_to '確認', attendance_review_user_path(attendance_request.user, date: attendance_request.worked_on), class: 'btn btn-primary' %></td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            </div>
          <% end %>  
        <div class="text-center">
          <%= f.submit '変更を送信する', class: 'btn btn-primary btn-lg' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/approved_logs.html.erb
<% provide(:title, @user.name) %>
<h1 class="modal-title">勤怠変更履歴</h1>

<%= link_to "リセット", reset_approved_logs_user_attendance_path(@user), method: :delete, data: {confirm: "本当に履歴をリセットしますか？"}, class: 'btn btn-primary' %>

<div>
  <%= form_with(url: approved_logs_user_attendance_path(params[:user_id]), method: :get, local: true) do %>
    <table>
      <thead>
        <tr>
          <th>年</th>
          <th>月</th>
          <th></th>
        </tr>      
      </thead>
      <tbody>
        <tr>
          <td>
            <%= select_tag 'search[year]', options_for_select((Date.today.year - 5..Date.today.year).to_a.reverse.unshift('全体表示'), selected: params[:search].try(:[], :year)) %>     
          </td>
          <td>
            <%= select_tag 'search[month]', options_for_select((1..12).to_a, selected: params[:search].try(:[], :month)) %>
          </td>
          <td><%= submit_tag '検索', class: 'btn btn-primary' %></td>
        </tr>
      </tbody> 
    </table>
  <% end %>
  
  </div>
<table class="table">
  <thead>
    <tr>
      <th>日付</th>
      <th>変更前出社時間</th>
      <th>変更前退社時間</th>
      <th>変更後出社時間</th>
      <th>変更後退社時間</th>
      <th>承認者</th>
    </tr>
  </thead>
  <tbody>
    <% @approved_attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.worked_on %></td>
        <td><%= format_time(attendance.first_started_at_before_change) %></td>
        <td>
          <% if same_day?(attendance.first_finished_at_before_change, attendance.worked_on) %>
            <%= format_time(attendance.first_finished_at_before_change) %>
          <% else %>
            <%= format_time(attendance.first_finished_at_before_change, true) %>
          <% end %>
        </td>
        <td><%= format_time(attendance.started_at) %></td>
        <td>
          <% if same_day?(attendance.finished_at, attendance.worked_on) %>
            <%= format_time(attendance.finished_at) %>
          <% else %>
          <%= format_time(attendance.finished_at, true) %>
          <% end %>
        </td>
        <td><%= User.find(attendance.attendance_approver_id).name if attendance.attendance_approver_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
<div>
  <h1>勤怠編集画面</h1>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出勤時間</th>
        <th>退勤時間</th>
        <th>翌日</th>
        <th>在社時間</th>
        <th>備考</th>
        <th>指示者確認㊞</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendances[]", day do |attendance| %>
          <tr>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td><%= $days_of_the_week[day.worked_on.wday] %></td>
            <% if !current_user.admin? && (Date.current < day.worked_on) %>
              <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
              <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
            <% else %>
              <td><%= attendance.time_field :started_at, class: "form-control" %></td>
              <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
            <% end %>
            <td><%= attendance.check_box :next_day, class: "form-control" %></td>
            <td>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= working_times(day.started_at, day.finished_at) %>
              <% end %>
            </td>
            <td><%= attendance.text_field :note, class: "form-control" %></td>
            <td>
              <%= attendance.collection_select :attendance_approver_id, @superiors, :id, :name, { include_blank: '未設定'}, class: "form-control" %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div class="center">
  <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
  <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
</div>
<% end %>