config/routes.rb
Rails.application.routes.draw do

  resources :attendances, only: [] do
    member do
      patch :update_attendance_request
    end
  end

  resources :users do  # CSV出力用のルートを追加
    member do
      get :export_csv # CSV出力用のアクション名を選択
    end
  end

  get 'bases/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'working_employees', to: 'users#working_employees', as: 'working_employees'

  resources :users do
    collection { post :import} #CSVファイルインポート
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendance_review'
    end
    
    resources :attendances, only: :update do
      member do
        patch :update_attendance_request
        get :approved_logs
        delete :reset_approved_logs
      end
    end
  end

  resources :bases

  resources :overtime_requests, only: [:new, :create] do
    member do
      patch :update
      patch :approve_overtime
    end
  end

  resources :monthly_approvals, only: [:create, :update]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップへ", root_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "ユーザー覧", users_path %></li>
            <li><%= link_to "出勤社員一覧", working_employees_path %></li>
            <li><%= link_to "拠点情報の修正", bases_path %></li>
            <li><%= link_to "基本情報の修正", edit_basic_info_user_path(current_user) %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% unless current_user.admin? %>
                <li><%= link_to "勤怠", current_user %></li>
              <% end %>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!-- HTML shimがこの1行で収まる -->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <!-- headerの内容がこの1行で収まる -->
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>